export const EVALUATION_STEPS: string[] = ["A", "B", "C"];
export const EVALUATION_LEVELS: string[] = ["ONE", "TWO"];
export const COMPETENCIES: string[] = [
  "MATHEMATICS",
  "SCIENTIFICMETHOD",
  "PROGRAMMING",
  "DATAANALYSIS",
  "MODELING",
  "LABORATORY",
  "DESIGN",
  "SYSTEMSTHINKING",
  "ALGORITHMS",
  "TECHNOLOGY",
  "CRITICALTHINKING",
  "QUANTITATIVE",
  "QUALITATIVE",
  "RESEARCH",
  "TROUBLESHOOTING",
  "COMMUNICATION",
  "COLLABORATION",
  "PROJECTMANAGEMENT",
  "ETHICS",
  "CREATIVITY",
  "ADAPTABILITY",
  "LIFELONGLEARNING",
];
export const ROLE_OPTIONS: string[] = ["ADMIN", "SUPERVISOR", "STUDENT"];

export const LEVEL_MAP = {
  FAIL: "0",
  ONE: "1",
  TWO: "2",
  READY_TO_PROCEED: "3",
};

export const STEP_MAP = {
  A: "1",
  B: "2",
  C: "3",
};
